CREATE TABLE thoughtful_moods(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mood TEXT NOT NULL,
    users_id INTEGER REFERENCES thoughtful_users(id) ON DELETE CASCADE NOT NULL
);

ALTER TABLE thoughtful_thoughts
    ADD COLUMN 
        moodId INTEGER REFERENCES thoughtful_moods(id)
        ON DELETE SET NULL;